### ISSUE TITLE
从不支持 BTN 的旧版本直接升级镜像到最新版本会因为配置文件中缺少 BTN 相关配置而启动失败

### ISSUE THREAD

**Issue by dousha** [PBH-BTN/PeerBanHelper#117]
<details>
<summary>Stacktrace</summary>

```text
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.bspfsystems.yamlconfiguration.configuration.ConfigurationSection.getBoolean(String)" because "section" is null
        at com.ghostchu.peerbanhelper.Main.main(Main.java:98)
Caused by: java.lang.NullPointerException: Cannot invoke "org.bspfsystems.yamlconfiguration.configuration.ConfigurationSection.getBoolean(String)" because "section" is null
        at com.ghostchu.peerbanhelper.btn.BtnNetwork.<init>(BtnNetwork.java:45)
        at com.ghostchu.peerbanhelper.PeerBanHelperServer.setupBtn(PeerBanHelperServer.java:169)
        at com.ghostchu.peerbanhelper.PeerBanHelperServer.<init>(PeerBanHelperServer.java:117)
        at com.ghostchu.peerbanhelper.Main.main(Main.java:95)

```

</details>

**Comment by Ghost-chu** [comment]
这已经是史前版本了，暂不考虑修复该问题。  
新的版本已经支持配置文件自动升级。
