### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by MononeV** [PBH-BTN/PeerBanHelper#190]
Rule metrics頁面為空，僅有的幾條訂閱匹配顯示
![image](https://github.com/PBH-BTN/PeerBanHelper/assets/39477101/ab08db84-05f6-43f0-9569-02d1012a65c9)
日誌循環報錯
```
[09:09:37] [JettyServerThreadPool-Virtual-37/WARN]: 500 Internal Server Error
java.lang.NullPointerException: null
	at java.base/java.util.Map.of(Unknown Source) ~[?:?]
	at com.ghostchu.peerbanhelper.util.rule.RuleMatcher.metadata(RuleMatcher.java:34) ~[PeerBanHelper.jar:4.2.2]
	at com.ghostchu.peerbanhelper.module.impl.webapi.PBHMetricsController.lambda$handleRules$0(PBHMetricsController.java:53) ~[PeerBanHelper.jar:4.2.2]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?]
	at com.ghostchu.peerbanhelper.module.impl.webapi.PBHMetricsController.handleRules(PBHMetricsController.java:56) ~[PeerBanHelper.jar:4.2.2]
	at io.javalin.router.Endpoint.handle(Endpoint.kt:52) ~[PeerBanHelper.jar:4.2.2]
	at io.javalin.router.ParsedEndpoint.handle(ParsedEndpoint.kt:15) ~[PeerBanHelper.jar:4.2.2]
	at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$9$lambda$7$lambda$6(DefaultTasks.kt:52) ~[PeerBanHelper.jar:4.2.2]
	at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:99) ~[PeerBanHelper.jar:4.2.2]
	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:64) ~[PeerBanHelper.jar:4.2.2]
	at io.javalin.http.servlet.JavalinServlet.handle(JavalinServlet.kt:50) ~[PeerBanHelper.jar:4.2.2]
	at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:30) ~[PeerBanHelper.jar:4.2.2]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587) ~[PeerBanHelper.jar:4.2.2]
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:52) ~[PeerBanHelper.jar:4.2.2]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[PeerBanHelper.jar:4.2.2]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[PeerBanHelper.jar:4.2.2]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.lang.VirtualThread.run(Unknown Source) ~[?:?]
```

**Comment by Ghost-chu** [comment]
@PluieM

**Comment by PluieM** [comment]
昨晚第二次PR已修正显示为null的问题
