### ISSUE TITLE
[BUG] BtnAbilitySubmitBans 异常处理

### ISSUE THREAD

**Issue by paulzzh** [PBH-BTN/PeerBanHelper#298]
### 版本号 - Version

5.1.0 (9eb338a7)

### 操作系统平台和系统架构 - OS  and CPU Arch

Ubuntu LXC x64

### 部署方式 - Deploy method

java -jar
systemd运行

### 关联的下载器类型 - Downloader Type

qBittorrentEE

### 问题描述 - Issue Description

BTN的封禁上报能力存在问题，抛出异常后不会在日志内展现，且影响后续上报
Executor没有正确使用
https://github.com/PBH-BTN/PeerBanHelper/blob/87cc5912c74da3e701cb2f136efc9d6931f76679/src/main/java/com/ghostchu/peerbanhelper/btn/ability/BtnAbilitySubmitBans.java#L41-L55
<img width="660" alt="3d07def37d3683ae77070bbded586f79" src="https://github.com/user-attachments/assets/ce3c0ea9-77c3-45cf-98e3-e7d2ee363e5b">

### 复现步骤 - Reproduce steps

1. 配置好BTN 然后启动PBH
2. 等待600s 连接到BTN
3. 等待900s 准备上报封禁信息 日志没有提示上报状态
4. 无限等待 重启前再也不会上报封禁信息

### 截图/日志文件 - Screenshot / Logs 

```
[arthas@14859]$ watch com.ghostchu.peerbanhelper.btn.ability.BtnAbilitySubmitBans generateBans "{throwExp}" -e -x 4
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 61 ms, listenerId: 17
method=com.ghostchu.peerbanhelper.btn.ability.BtnAbilitySubmitBans.generateBans location=AtExceptionExit
ts=2024-08-02 20:07:48; [cost=2.728463ms] result=@ArrayList[
    java.lang.NullPointerException: Cannot invoke "java.util.BitSet.get(int)" because "this.peerFlags" is null
        at com.ghostchu.peerbanhelper.peer.PeerFlag.isInteresting(PeerFlag.java:53)
        at com.ghostchu.peerbanhelper.peer.PeerFlag.toString(PeerFlag.java:163)
        at com.ghostchu.peerbanhelper.btn.ping.BtnPeer.from(BtnPeer.java:63)
        at com.ghostchu.peerbanhelper.btn.ability.BtnAbilitySubmitBans.lambda$generateBans$2(BtnAbilitySubmitBans.java:84)
        at java.base/java.util.Map.forEach(Map.java:733)
        at com.ghostchu.peerbanhelper.btn.ability.BtnAbilitySubmitBans.generateBans(BtnAbilitySubmitBans.java:84)
        at com.ghostchu.peerbanhelper.btn.ability.BtnAbilitySubmitBans.submit(BtnAbilitySubmitBans.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
,
]
```

### 额外信息 - Addition Information

Executors内抛出异常后不会打印在日志中，且会阻止后续计划调用
https://stackoverflow.com/questions/6894595/scheduledexecutorservice-exception-handling

造成空指针的相关commit https://github.com/PBH-BTN/PeerBanHelper/commit/5fa42aa3c1dc8eba37906fbf8a3ca91ccbf951ab

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by paulzzh** [comment]
重装 清除数据后 恢复正常
但是Executor异常后不继续调用的风险仍然存在
