### ISSUE TITLE
[BUG] startup error

### ISSUE THREAD

**Issue by Unihis** [PBH-BTN/PeerBanHelper#322]
### 版本号 - Version

5.1.0

### 操作系统平台和系统架构 - OS  and CPU Arch

windows x64

### 部署方式 - Deploy method

windows.exe install

### 关联的下载器类型 - Downloader Type

qBittorrent

### 问题描述 - Issue Description

开机自动启动报错，重启软件也同样报错

### 复现步骤 - Reproduce steps

未知

### 截图/日志文件 - Screenshot / Logs 

[09:58:51] [main/ERROR]: Failed to start Javalin

[09:58:51] [main/ERROR]: Failed to startup PeerBanHelper, FATAL ERROR
io.javalin.util.JavalinBindException: Port already in use. Make sure no other process is using port 9898 and try again.
	at io.javalin.jetty.JettyServer.start(JettyServer.kt:101) ~[PeerBanHelper.jar:5.1.0]
	at io.javalin.Javalin.start(Javalin.java:109) ~[PeerBanHelper.jar:5.1.0]
	at com.ghostchu.peerbanhelper.web.JavalinWebContainer.start(JavalinWebContainer.java:155) ~[PeerBanHelper.jar:5.1.0]
	at com.ghostchu.peerbanhelper.PeerBanHelperServer.registerHttpServer(PeerBanHelperServer.java:327) ~[PeerBanHelper.jar:5.1.0]
	at com.ghostchu.peerbanhelper.PeerBanHelperServer.start(PeerBanHelperServer.java:145) ~[PeerBanHelper.jar:5.1.0]
	at com.ghostchu.peerbanhelper.Main.main(Main.java:119) [PeerBanHelper.jar:5.1.0]
	at com.ghostchu.peerbanhelper.MainJumpLoader.main(MainJumpLoader.java:17) [PeerBanHelper.jar:5.1.0]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84) [i4jruntime.jar:?]
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94) [i4jruntime.jar:?]
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25) [i4jruntime.jar:?]
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:9898
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[PeerBanHelper.jar:5.1.0]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304) ~[PeerBanHelper.jar:5.1.0]
	at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402) ~[PeerBanHelper.jar:5.1.0]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.eclipse.jetty.server.Server.doStart(Server.java:398) ~[PeerBanHelper.jar:5.1.0]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[PeerBanHelper.jar:5.1.0]
	at io.javalin.jetty.JettyServer.start(JettyServer.kt:93) ~[PeerBanHelper.jar:5.1.0]
	... 11 more
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at java.base/sun.nio.ch.Net.bind(Net.java:565) ~[?:?]
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344) ~[?:?]
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:339) ~[PeerBanHelper.jar:5.1.0]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304) ~[PeerBanHelper.jar:5.1.0]
	at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402) ~[PeerBanHelper.jar:5.1.0]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.eclipse.jetty.server.Server.doStart(Server.java:398) ~[PeerBanHelper.jar:5.1.0]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[PeerBanHelper.jar:5.1.0]
	at io.javalin.jetty.JettyServer.start(JettyServer.kt:93) ~[PeerBanHelper.jar:5.1.0]
	... 11 more

### 额外信息 - Addition Information

提交此次报错后尝试重启电脑，等我消息

### 检查清单 - Check list

- [ ] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [ ] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [ ] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [ ] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Unihis** [comment]
重启电脑后问题解决

**Comment by Ghost-chu** [comment]
您可能启动了多个 PBH 进程或者有其他程序占用 9898 端口。
