### ISSUE TITLE
[BUG] Failed to startup PeerBanHelper

### ISSUE THREAD

**Issue by wannacry601** [PBH-BTN/PeerBanHelper#338]
### 版本号 - Version

v6.0.1

### 操作系统平台和系统架构 - OS  and CPU Arch

Windows 11 x64

### 部署方式 - Deploy method

Windows 安装程序（通过 .exe 安装）

### 关联的下载器类型 - Downloader Type

qBittorrent

### 问题描述 - Issue Description

在第一次部署完成后，退出重新进入时报错

### 复现步骤 - Reproduce steps

1. 第一次通过安装程序安装
2. 打开WebUI部署完成，添加下载器成功
3. 退出重新进入时报错
4. 之后多次尝试重新打开程序均报错，重启电脑依然报错

### 截图/日志文件 - Screenshot / Logs 

[main/ERROR]: Failed to startup PeerBanHelper, FATAL ERROR
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because the return value of "org.bspfsystems.yamlconfiguration.configuration.ConfigurationSection.getString(String)" is null
	at com.ghostchu.peerbanhelper.PeerBanHelperServer.createDownloader(PeerBanHelperServer.java:195) ~[PeerBanHelper.jar:6.0.1]
	at com.ghostchu.peerbanhelper.PeerBanHelperServer.loadDownloaders(PeerBanHelperServer.java:187) ~[PeerBanHelper.jar:6.0.1]
	at com.ghostchu.peerbanhelper.PeerBanHelperServer.start(PeerBanHelperServer.java:157) ~[PeerBanHelper.jar:6.0.1]
	at com.ghostchu.peerbanhelper.Main.main(Main.java:121) [PeerBanHelper.jar:6.0.1]
	at com.ghostchu.peerbanhelper.MainJumpLoader.main(MainJumpLoader.java:17) [PeerBanHelper.jar:6.0.1]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84) [i4jruntime.jar:?]
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94) [i4jruntime.jar:?]
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25) [i4jruntime.jar:?]

### 额外信息 - Addition Information

昨天使用5.1.0版本，今天更新到v6.0.1，均有此问题

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [ ] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [ ] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
给下载器起名字的时候加 `.` 了？

**Comment by wannacry601** [comment]
> 给下载器起名字的时候加 `.` 了？
没有，但是加了空格，是不是这个的原因？

**Comment by Ghost-chu** [comment]
> > 给下载器起名字的时候加 `.` 了？
> > 没有，但是加了空格，是不是这个的原因？

空格应该没有影响，你添加的什么下载器？
