### ISSUE TITLE
[Other] 卡死问题

### ISSUE THREAD

**Issue by starobots** [PBH-BTN/PeerBanHelper#728]
### 问题描述 - Issue Description

运行三小时左右，就一直报这个错误，然后qbt和pb就都一起卡死，qbt卡住没有上传。

[09:46:36] [virtual-80/ERROR]: Unable to complete scheduled tasks
java.util.concurrent.CompletionException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(CompletableFuture.java:323)
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:421)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1196)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:554)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2238)
	at java.net.http/jdk.internal.net.http.Exchange.checkCancelled(Exchange.java:335)
	at java.net.http/jdk.internal.net.http.Exchange.cancel(Exchange.java:298)
	at java.net.http/jdk.internal.net.http.MultiExchange.cancel(MultiExchange.java:266)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectTimerEvent.handle(PlainHttpConnection.java:103)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1790)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1387)
	Suppressed: java.lang.RuntimeException: java.util.concurrent.CompletionException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
		at com.ghostchu.peerbanhelper.module.impl.rule.IPBlackRuleList.lambda$updateRule$9(IPBlackRuleList.java:222)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:907)
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:885)
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:554)
		at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:658)
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:958)
		at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:526)
		at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
		at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
	Caused by: [CIRCULAR REFERENCE: java.util.concurrent.CompletionException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out]
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:620)
	at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:565)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:485)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:978)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:955)
	... 8 common frames omitted
Caused by: java.net.ConnectException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:621)
	... 12 common frames omitted

### 额外信息 - Addition Information

win10，qbt4.6.7，pb 7.1.3，全都是默认设置，只把检测时间改成1分钟，60000ms。

### 检查清单 - Check list

- [ ] 这不是一个错误 （BUG） (This is not an bug/error)
- [ ] PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)
- [ ] 我已检查过 [PBH 文档](https://docs.pbh-btn.com/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://docs.pbh-btn.com/))
- [ ] 我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规、黑灰产、危害国家安全、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布了这些内容，我的账号将立刻从包括但不限于 PBH-BTN 组织、社交软件中封禁。所有主题、内容都将被立刻删除或折叠，撤销、删除和收回您所做出的一切贡献，并封禁 BTN 网络的中账号权限、排除您所提交的所有数据。在您违反相关规则时，PBH-BTN 将会将您的注册、登录、和最近访问的 IP 地址、电子邮件地址、以及其它可能追踪您或将您去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知的提供这些数据。 (I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as “taunting, name-calling, war-mongering, open-boxing (sometimes referred to as mansplaining), personal attacks, hatred, violence, insulting language, illegal activities, black and grey business, endangering national security, and committing or assisting others in committing telecommunication crimes”. I am aware that if I continue to post such content, my account will be immediately banned from organizations including but not limited to PBH-BTN, social software. All topics and content will be immediately deleted or collapsed, all contributions will be revoked, deleted and retracted, and you will be banned from the BTN network and all data you have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will delete your registration, login, and most recent IP address, email address, and any other information that may be used to track you or de-anonymize you from regular to permanent deletion, and will make this data available to the government, public security, or other relevant authorities without notice if they request it, no matter what country or region.)

**Comment by Ghost-chu** [comment]
请下次包含错误时选择 BUG 反馈模板。

该错误与您的网络环境有关，PBH 无法连接到您的下载器，这不是PBH的问题，请检查网络和下载器状态。
